import { Type, Types } from "./Type";

export const POITypes: Type[] = 
    [
        {description: "City name (Point, fat, big)", type:256},
        {description: "City name (Point, big)", type:1536},
        {description: "City name (Point, small)", type:2816},
        {description: "City name (Point, small)", type:3072},
        {description: "City name (Point, small)", type:2328},
        {description: "City name (Point, big)", type:3584},
        {description: "Region name (no Point, big)", type:5120},
        {description: "Region name (no Point, middle)", type:7680},
        {description: "Exit", type:8192},
        {description: "Exit (Service)", type:8463},
        {description: "Exit (with facilities)", type:3584},
        {description: "Exit (Restroom)", type:8704},
        {description: "Exit (Convenience Store)", type:8960},
        {description: "Exit (Weight Station)", type:9216},
        {description: "Exit (Toll Booth)", type:9472},
        {description: "Exit (Information)", type:9728},
        {description: "Exit", type:9984},
        {description: "Region name (no Point, small)", type:10240},
        {description: "Dining (Other)", type:10752},
        {description: "Dining (American)", type:10753},
        // {description: "", type:},
        // {description: "", type:},
        // {description: "", type:},
        // {description: "", type:},
        // {description: "", type:},
        // {description: "", type:},
        // {description: "", type:},
        // {description: "", type:},
        // {description: "", type:},
        // {description: "", type:},
        // {description: "", type:},
        // {description: "", type:},
        // {description: "", type:},
        // {description: "", type:},
       
    ]