import { Type, Types } from "./Type";

export const polylineTypes: Type[] = 
    [
        {description: "Major Highway-thick", type: 1},
        {description: "Principal Highway-thick", type: 2},
        {description: "Principal Highway-medium", type: 3},
        {description: "Arterial Road–medium", type: 4},
        {description: "Arterial Road-thick", type: 5},
        {description: "Road-thin", type: 6},
        {description: "Alley-thick", type: 7},
        {description: "Ramp", type: 8},
        {description: "Ramp", type: 9},
        {description: "Unpaved Road-thin", type: 10},
        {description: "Major Highway Connector-thick", type: 11},
        {description: "Roundabout", type: 12},
        {description: "Railroad", type: 20},
        {description: "Shoreline", type: 21},
        {description: "Track/Trail", type: 22},
        {description: "Stream-thin", type: 24},
        {description: "Time-Zone", type: 25},
        {description: "Ferry", type: 26},
        {description: "Ferry", type: 27},
        {description: "Political Boundary", type: 28},
        {description: "County Boundary", type: 29},
        {description: "International Boundary", type: 30},
        {description: "River", type: 31},
        {description: "Land Contour (thin)", type: 32},
        {description: "Land Contour (medium)", type: 33},
        {description: "Land Contour (thick)", type: 34},
        {description: "Depth Contour (thin)", type: 35},
        {description: "Depth Contour (medium)", type: 36},
        {description: "Depth Contour (thick)", type: 37},
        {description: "Intermittent River", type: 38},
        {description: "Airport Runway", type: 39},
        {description: "Pipeline", type: 40},
        {description: "Power line", type: 41},
        {description: "Marine Boundary (no line)", type: 42},
        {description: "Marine Hazard (no line)", type: 43},
        {description: "Miscellaneous line", type: 256},
        {description: "Line", type: 257},
        {description: "Cartographic line", type: 258},
        {description: "Road", type: 259},
        {description: "Clearing line", type: 260},
        {description: "Contour line", type: 261},
        {description: "Overhead cable", type: 262},
        {description: "Bridge", type: 263},
        {description: "Recommended route", type: 264},
        {description: "Chart border", type: 265},
        {description: "Depth contour", type: 768},
        {description: "Depth contour value", type: 769},
        {description: "Intertidal zone border", type: 775},
        {description: "Obstruction line", type: 1024},
        {description: "Submarine cable", type: 1025},
        {description: "Submarine pipeline", type: 1026},
        {description: "Pile barrier", type: 1027},
        {description: "Fishing stakes", type: 1028},
        {description: "Supply pipeline area", type: 1029},
        {description: "Submarine cable area", type: 1030},
        {description: "Dumping ground", type: 1031},
        {description: "Explosive dumping ground", type: 1032},
        {description: "Danger line", type: 1033},
        {description: "Overhead cable", type: 1034},
        {description: "Submerged construction", type: 1035},
        {description: "Pier/jetty", type: 1036},
        {description: "Restriction", type: 1280},
        {description: "Anchoring prohibited", type: 1281},
        {description: "Fishing prohibited", type: 1282},
        {description: "Prohibited area", type: 1283},
        {description: "Military practice area", type: 1284},
        {description: "Anchoring and fishing prohibited", type: 1285},
        {description: "Limit of nature reservation", type: 1286},
        {description: "Restricted area", type: 1287},
        {description: "Minefield", type: 1288},
        {description: "Miscellaneous line", type: 1536},
        {description: "Cartographic line", type: 1537},
        {description: "Traffic separation line", type: 1538},
        {description: "International maritime boundary", type: 1539},
        {description: "Straight territorial sea baseline", type: 1540},
        {description: "Seaward limit of territorial sea", type: 1541},
        {description: "Anchorage area", type: 1542},
        {description: "Quarantine anchorage area", type: 1543},
        {description: "Fishery zone", type: 1544},
        {description: "Swept area", type: 1545},
        {description: "Traffic separation zone", type: 1546},
        {description: "Limit of exclusive economic zone", type: 1547},
        {description: "Established direction of traffic flow", type: 1548},
        {description: "Recommended direction of traffic flow", type: 1549},
        {description: "Harbour limit", type: 1550},
        {description: "Inadequately surveyed area", type: 1551},
        {description: "Inshore traffic zone", type: 1552},
        {description: "Limit of traffic lane", type: 1553},
        {description: "River channel", type: 1793},
        {description: "Submerged object", type: 1794},
        {description: "Chart boundary", type: 1795},
        {description: "Chart boundary", type: 1796},
        {description: "Chart boundary", type: 1797},
        {description: "Chart boundary", type: 1798}
    ]