import { Type, Types } from "./Type";

export const polygoneTypes: Type[] = 
    [
        {description: "City", type: 1},
        {description: "City", type: 2},
        {description: "City", type: 3},
        {description: "Military", type: 4},
        {description: "Car Park (Parking Lot)", type: 5},
        {description: "Parking Garage", type: 6},
        {description: "Airport", type: 7},
        {description: "Shopping Centre", type: 8},
        {description: "Marina", type: 9},
        {description: "University", type: 10},
        {description: "Hospital", type: 11},
        {description: "Industrial", type: 12},
        {description: "Reservation", type: 13},
        {description: "Airport Runway", type: 14},
        {description: "Man made area", type: 19},
        {description: "National park", type: 20},
        {description: "National park", type: 21},
        {description: "National park", type: 22},
        {description: "City Park", type: 23},
        {description: "Golf", type: 24},
        {description: "Sport", type: 25},
        {description: "Cemetery", type: 26},
        {description: "State Park", type: 30},
        {description: "State Park", type: 31},
        {description: "Ocean", type: 40},
        {description: "Sea", type: 50},
        {description: "Blue-Unknown", type: 59},
        {description: "Lake", type: 60},
        {description: "Lake", type: 61},
        {description: "Lake", type: 62},
        {description: "Lake", type: 63},
        {description: "Lake", type: 64},
        {description: "Lake", type: 65},
        {description: "Lake", type: 66},
        {description: "Lake", type: 67},
        {description: "Lake", type: 68},
        {description: "Blue-Unknown", type: 69},
        {description: "River", type: 70},
        {description: "River", type: 71},
        {description: "River", type: 72},
        {description: "River", type: 73},
        {description: "Background", type: 75},
        {description: "Intermittent River/Lake", type: 76},
        {description: "Glacier", type: 77},
        {description: "Orchard or plantation", type: 78},
        {description: "Scrub", type: 79},
        {description: "Woods", type: 80},
        {description: "Wetland", type: 81},
        {description: "Tundra", type: 82},
        {description: "Flats", type: 83},
        {description: "Land - white", type: 256},
        {description: "Land - non-urban", type: 257},
        {description: "Land - urban", type: 258},
        {description: "Chart exclusion area", type: 259},
        {description: "Chart background", type: 260},
        {description: "Bridge", type: 261},
        {description: "Depth area - white 1", type: 768},
        {description: "Intertidal zone", type: 769},
        {description: "Depth area - blue 1", type: 770},
        {description: "Depth area - blue 2", type: 771},
        {description: "Depth area - blue 3", type: 772},
        {description: "Depth area - blue 4", type: 773},
        {description: "Depth area - blue 5", type: 774},
        {description: "Depth area - white", type: 775},
        {description: "Obstruction (invisible)", type: 1024},
        {description: "Submarine cable (invisible)", type: 1025},
        {description: "Submarine pipeline (invisible)", type: 1026},
        {description: "Pile barrier (invisible)", type: 1027},
        {description: "Fishing stakes (invisible)", type: 1028},
        {description: "Supply pipeline area/line (invisible)", type: 1029},
        {description: "Submarine cable area/line (invisible)", type: 1030},
        {description: "Dumping ground (invisible)", type: 1031},
        {description: "Explosive dumping ground (invisible)", type: 1032},
        {description: "Danger line (invisible)", type: 1033},
        {description: "Overhead cable (invisible)", type: 1034},
        {description: "Submerged construction (invisible)", type: 1035},
        {description: "Pier/jetty (invisible)", type: 1036},
        {description: "Restriction area/line (invisible)", type: 1280},
        {description: "Anchoring prohibited (invisible)", type: 1281},
        {description: "Fishing prohibited (invisible)", type: 1282},
        {description: "Prohibited area (invisible)", type: 1283},
        {description: "Military practice area (invisible)", type: 1284},
        {description: "Anchoring and fishing prohibited (invisible)", type: 1285},
        {description: "Limit of nature reservation (invisible)", type: 1286},
        {description: "Restricted area (invisible)", type: 1287},
        {description: "Minefield (invisible)", type: 1288},
        {description: "Miscellaneous area", type: 1536},
        {description: "Cartographic area", type: 1537},
        {description: "Traffic separation area", type: 1538},
        {description: "International maritime boundary", type: 1539},
        {description: "Straight territorial sea baseline", type: 1540},
        {description: "Seaward limit of territorial sea", type: 1541},
        {description: "Anchorage area", type: 1542},
        {description: "Quarantine anchorage area", type: 1543},
        {description: "Fishery zone", type: 1544},
        {description: "Swept area", type: 1545},
        {description: "Traffic separation zone", type: 1546},
        {description: "Limit of exclusive economic zone", type: 1547},
        {description: "Established direction of traffic flow", type: 1548},
        {description: "Fishing area", type: 1793},
        {description: "Restricted area", type: 1794},
        {description: "Anchorage area", type: 1795},
        {description: "Fishing Hot Spots chart", type: 1796}
    ]